Caption fixups for Lower Your Guards
lkuper/icfp2020-captions pull request #4
Opened 2020-09-03 22:50 UTC by RyanGlScott

cc @sgraf812

2020-09-04 09:19 UTC, sgraf812 requested changes
Thanks for doing this! I proof-read along with the audio and added my own changes as suggestions. Could you please accept them, too?

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
> +Dialogue: 0,1:49:43.32,1:49:45.24,Default,,0,0,0,,If you want to know about this part,
```suggestion
Dialogue: 0,1:49:43.32,1:49:45.24,Default,,0,0,0,,If you want to know more about this part,
```

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
> +Dialogue: 0,1:50:18.44,1:50:21.96,Default,,0,0,0,,and a view pattern that\N applies the matched thing to g
```suggestion
Dialogue: 0,1:50:18.44,1:50:21.96,Default,,0,0,0,,and a view pattern that\N applies g to the matched thing
```

I know this isn't entirely faithful to the audio, but as Simon suggested this is what I should have said.

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
>  Dialogue: 0,1:50:33.28,1:50:35.24,Default,,0,0,0,,Here is the syntax\N definition for reference.
```suggestion
Dialogue: 0,1:50:33.28,1:50:35.24,Default,,0,0,0,,Here is their syntax\N definition for reference.
```

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
>  Dialogue: 0,1:52:17.16,1:52:21.04,Default,,0,0,0,,as a fraction of them fall through\N from one clause to the next.
```suggestion
Dialogue: 0,1:52:17.16,1:52:21.04,Default,,0,0,0,,as a fraction of them falls through\N from one clause to the next.

```

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
>  Dialogue: 0,1:52:28.84,1:52:30.52,Default,,0,0,0,,We pick refinement\N types for the job.
```suggestion
Dialogue: 0,1:52:28.84,1:52:30.52,Default,,0,0,0,,We picked refinement\N types for the job.

```

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
>  Dialogue: 0,1:54:14.48,1:54:16.40,Default,,0,0,0,,and fall through the second branch.
```suggestion
Dialogue: 0,1:54:14.48,1:54:16.40,Default,,0,0,0,,can fall through the second branch.

```

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
> +Dialogue: 0,1:54:44.08,1:54:45.84,Default,,0,0,0,,And that'ss all there is\N to coverage checking.
```suggestion
Dialogue: 0,1:54:44.08,1:54:45.84,Default,,0,0,0,,And that's all there is\N to coverage checking.

```

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
> +Dialogue: 0,1:55:29.08,1:55:33.52,Default,,0,0,0,,And we think that FFI calls\N and serialization effects
```suggestion
Dialogue: 0,1:55:29.08,1:55:33.52,Default,,0,0,0,,And we think that FFI calls\N and serialization of facts

```

2020-09-04 09:19 UTC, sgraf812 commented on session4/session4.ass
>  Dialogue: 0,1:55:37.44,1:55:40.76,Default,,0,0,0,,and just wrote our own ad\N hoc generator function.
```suggestion
Dialogue: 0,1:55:37.44,1:55:40.76,Default,,0,0,0,,and just wrote our own \N ad-hoc generator function.

```

2020-09-04 11:34 UTC, RyanGlScott commented
Thanks, @sgraf812!

I think this should be ready to go now, but please shout if I messed up any of the `.ass`/`.srt` conventions.

2020-09-04 14:54 UTC, sgraf812 commented
LGTM!

2020-09-10 00:43 UTC, merged

2020-09-10 00:43 UTC, lkuper commented
Thanks!  (There was no need to update the .srt too, but it's not a problem that you did.)